root_folder: ./
epochs: 70
stages:
- 49
- 64
batch_size: 128
num_workers: 8

criterion_weight_base: 10
spatial_lambda_c_base: 3
rehearsal: 20
fixed_weight: True
pod_loss: True
type_update_criterion_weight: "cl2r"
use_partial_memory: False
cuda_device: "cuda:0"